import { describe, it, expect, afterEach } from "vitest";
import { exportToFlutter } from "./collectionToFlutter";
import { toAsciiIdentifier } from "./stringTransformation";

describe("toAsciiIdentifier", () => {
  it("strips diacritics and treats punctuation as word separators", () => {
    expect(toAsciiIdentifier("colors-ação")).toBe("colorsAcao");
    expect(toAsciiIdentifier("spacing-4 (compact)")).toBe("spacing4Compact");
    expect(toAsciiIdentifier("colors-blue-500")).toBe("colorsBlue500");
  });

  it("keeps inner capitalization of camelCase segments", () => {
    expect(toAsciiIdentifier("fontFamily-sans")).toBe("fontFamilySans");
  });

  it("never returns an empty identifier", () => {
    expect(toAsciiIdentifier("!!!")).toBe("token");
  });
});

function makeFigmaMock() {
  const collection = {
    id: "c1",
    name: "Primitives",
    modes: [
      { name: "Light", modeId: "L" },
      { name: "Dark", modeId: "D" },
    ],
    variableIds: ["blue500", "overlayDim", "spacing4", "fontSizeBody", "familySans", "bgPrimary"],
  };

  const vars: Record<string, any> = {
    blue500: {
      name: "Colors/Blue/500",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { r: 0, g: 0, b: 1, a: 1 },
        D: { r: 0, g: 0, b: 0.2, a: 1 },
      },
    },
    overlayDim: {
      name: "Overlay/Dim",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { r: 0, g: 0, b: 0, a: 0.5 },
        D: { r: 0, g: 0, b: 0, a: 0.5 },
      },
    },
    spacing4: {
      name: "Spacing/4",
      resolvedType: "FLOAT",
      variableCollectionId: "c1",
      valuesByMode: { L: 16, D: 16 },
    },
    fontSizeBody: {
      name: "Font Size/Body",
      resolvedType: "FLOAT",
      variableCollectionId: "c1",
      valuesByMode: { L: 14, D: 14 },
    },
    familySans: {
      name: "Font Family/Sans",
      resolvedType: "STRING",
      variableCollectionId: "c1",
      valuesByMode: { L: "Inter", D: "Inter" },
    },
    bgPrimary: {
      name: "Background/Primary",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { type: "VARIABLE_ALIAS", id: "blue500" },
        D: { type: "VARIABLE_ALIAS", id: "blue500" },
      },
    },
  };

  return {
    variables: {
      getLocalVariableCollectionsAsync: async () => [collection],
      getVariableByIdAsync: async (id: string) => vars[id] ?? null,
      getVariableCollectionByIdAsync: async (id: string) => (id === "c1" ? collection : null),
    },
  };
}

describe("exportToFlutter", () => {
  afterEach(() => {
    delete (globalThis as any).figma;
  });

  it("emits a ThemeExtension subclass, the documented mechanism for custom tokens", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter();

    expect(result).toContain("// Flutter tokens generated by Variform.");
    expect(result).toContain("import 'package:flutter/material.dart';");
    expect(result).toContain("class Tokens extends ThemeExtension<Tokens> {");
    // Header documents the official light/dark wiring (theme + darkTheme).
    expect(result).toContain("theme: ThemeData(brightness: Brightness.light, extensions: [Tokens.light])");
    expect(result).toContain("darkTheme: ThemeData(brightness: Brightness.dark, extensions: [Tokens.dark])");
    expect(result).toContain("Theme.of(context).extension<Tokens>()!");
    expect(result).not.toContain("import(");
  });

  it("declares a typed final field per token, named camelCase of category + path", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter();

    expect(result).toContain("required this.colorsBlue500,");
    expect(result).toContain("final Color colorsBlue500;");
    expect(result).toContain("final Color colorsOverlayDim;");
    expect(result).toContain("final double spacing4;");
    // "Font Size/Body" categorizes as fontSize (the typography branch wins over 'size').
    expect(result).toContain("final double fontSizeBody;");
    expect(result).toContain("final String fontFamilySans;");
    // "Background/Primary" categorizes as colors (the 'background' keyword).
    expect(result).toContain("final Color colorsBackgroundPrimary;");
  });

  it("emits one static const instance per mode, default (light) before dark", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter();

    expect(result.indexOf("static const Tokens light = Tokens(")).toBeGreaterThan(-1);
    expect(result.indexOf("static const Tokens light = Tokens("))
      .toBeLessThan(result.indexOf("static const Tokens dark = Tokens("));

    const light = result.slice(result.indexOf("static const Tokens light"), result.indexOf("static const Tokens dark"));
    expect(light).toContain("colorsBlue500: Color(0xFF0000FF),");
    expect(light).toContain("colorsOverlayDim: Color(0x80000000),");
    expect(light).toContain("spacing4: 16.0,");
    expect(light).toContain("fontFamilySans: 'Inter',");

    // Dark variant holds the dark values until the copyWith override starts.
    const dark = result.slice(result.indexOf("static const Tokens dark"), result.indexOf("Tokens copyWith"));
    expect(dark).toContain("colorsBlue500: Color(0xFF000033),");
    expect(dark).toContain("colorsBackgroundPrimary: Color(0xFF000033),");
    expect(dark).not.toContain("0xFF0000FF");
  });

  it("resolves aliases to the terminal color value in each instance", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter();

    expect(result).toContain("colorsBackgroundPrimary: Color(0xFF0000FF),");
    expect(result).not.toContain("VARIABLE_ALIAS");
  });

  it("implements copyWith with nullable fields, as ThemeExtension requires", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter();

    expect(result).toContain("Tokens copyWith({");
    expect(result).toContain("        Color? colorsBlue500,");
    expect(result).toContain("colorsBlue500: colorsBlue500 ?? this.colorsBlue500,");
  });

  it("implements lerp: colors and doubles interpolate, strings snap at t < 0.5", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter();

    expect(result).toContain("Tokens lerp(ThemeExtension<Tokens>? other, double t) {");
    expect(result).toContain("if (other is! Tokens) return this;");
    expect(result).toContain("Color.lerp(colorsBlue500, other.colorsBlue500, t)!");
    expect(result).toContain("lerpDouble(spacing4, other.spacing4, t)!");
    expect(result).toContain("t < 0.5 ? fontFamilySans : other.fontFamilySans");
    // lerpDouble comes from dart:ui, imported only because doubles exist.
    expect(result).toContain("import 'dart:ui' show lerpDouble;");
    expect(result).not.toContain("import(");
  });

  it("applies the prefix to the family segment", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter(undefined, "acme");

    expect(result).toContain("colorsAcmeBlue500");
    expect(result).not.toContain("colorsBlue500");
  });

  it("emits a single instance and no darkTheme wiring when one mode is selected", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter({ c1: ["L"] });

    expect(result).toContain("static const Tokens light = Tokens(");
    expect(result).not.toContain("Tokens.dark");
    expect(result).not.toContain("darkTheme");
  });

  it("escapes backslashes, apostrophes and $ in string values", async () => {
    (globalThis as any).figma = {
      variables: {
        getLocalVariableCollectionsAsync: async () => [
          {
            id: "c1",
            name: "Primitives",
            modes: [{ name: "Light", modeId: "L" }],
            variableIds: ["label"],
          },
        ],
        getVariableByIdAsync: async (id: string) =>
          id === "label"
            ? {
                name: "Font Family/Label",
                resolvedType: "STRING",
                variableCollectionId: "c1",
                valuesByMode: { L: "it's $100\\path" },
              }
            : null,
        getVariableCollectionByIdAsync: async () => null,
      },
    };
    const result = await exportToFlutter();

    // Backslash first (doubled), then apostrophe, then $ — a literal Dart string.
    expect(result).toContain("fontFamilyLabel: 'it\\'s \\$100\\\\path',");
    // No FLOAT tokens here, so the dart:ui import is omitted.
    expect(result).not.toContain("dart:ui");
    expect(result).not.toContain("import(");
  });

  it("escapes newlines and carriage returns in string values", async () => {
    (globalThis as any).figma = {
      variables: {
        getLocalVariableCollectionsAsync: async () => [
          {
            id: "c1",
            name: "Primitives",
            modes: [{ name: "Light", modeId: "L" }],
            variableIds: ["label"],
          },
        ],
        getVariableByIdAsync: async (id: string) =>
          id === "label"
            ? {
                name: "Font Family/Label",
                resolvedType: "STRING",
                variableCollectionId: "c1",
                valuesByMode: { L: "first\nsecond\r\nthird" },
              }
            : null,
        getVariableCollectionByIdAsync: async () => null,
      },
    };
    const result = await exportToFlutter();

    // A literal line break would terminate the Dart string literal.
    expect(result).toContain("fontFamilyLabel: 'first\\nsecond\\r\\nthird',");
    expect(result).not.toContain("first\nsecond");
  });

  it("keeps exponential notation for very large FLOATs (no dangling .0)", async () => {
    (globalThis as any).figma = {
      variables: {
        getLocalVariableCollectionsAsync: async () => [
          {
            id: "c1",
            name: "Primitives",
            modes: [{ name: "Light", modeId: "L" }],
            variableIds: ["huge"],
          },
        ],
        getVariableByIdAsync: async (id: string) =>
          id === "huge"
            ? {
                name: "Spacing/Huge",
                resolvedType: "FLOAT",
                variableCollectionId: "c1",
                valuesByMode: { L: 1e21 },
              }
            : null,
        getVariableCollectionByIdAsync: async () => null,
      },
    };
    const result = await exportToFlutter();

    // Number.isInteger(1e21) is true, so the old check emitted "1e+21.0",
    // which is not a valid Dart literal.
    expect(result).toContain("spacingHuge: 1e+21,");
    expect(result).not.toContain("1e+21.0");
  });

  it("sanitizes accented and punctuation-heavy names to ASCII identifiers", async () => {
    (globalThis as any).figma = {
      variables: {
        getLocalVariableCollectionsAsync: async () => [
          {
            id: "c1",
            name: "Primitives",
            modes: [{ name: "Light", modeId: "L" }],
            variableIds: ["acao", "compact"],
          },
        ],
        getVariableByIdAsync: async (id: string) =>
          ({
            acao: {
              name: "Colors/Ação",
              resolvedType: "COLOR",
              variableCollectionId: "c1",
              valuesByMode: { L: { r: 1, g: 0, b: 0, a: 1 } },
            },
            compact: {
              name: "Spacing/4 (compact)",
              resolvedType: "FLOAT",
              variableCollectionId: "c1",
              valuesByMode: { L: 8 },
            },
          } as any)[id] ?? null,
        getVariableCollectionByIdAsync: async () => null,
      },
    };
    const result = await exportToFlutter();

    // Dart identifiers are ASCII-only: "colorsAção" would not compile.
    expect(result).toContain("final Color colorsAcao;");
    expect(result).toContain("final double spacing4Compact;");
    expect(result).toContain("colorsAcao: Color(0xFFFF0000),");
    expect(result).toContain("spacing4Compact: 8.0,");
    expect(result).not.toContain("Ação");
    expect(result).not.toContain("(compact)");
  });

  it("suffixes duplicate field names so the class compiles", async () => {
    (globalThis as any).figma = {
      variables: {
        getLocalVariableCollectionsAsync: async () => [
          {
            id: "c1",
            name: "Primitives",
            modes: [{ name: "Light", modeId: "L" }],
            variableIds: ["a", "b"],
          },
        ],
        getVariableByIdAsync: async (id: string) =>
          ({
            a: {
              name: "Colors/Blue 500",
              resolvedType: "COLOR",
              variableCollectionId: "c1",
              valuesByMode: { L: { r: 0, g: 0, b: 1, a: 1 } },
            },
            b: {
              name: "Colors/Blue-500",
              resolvedType: "COLOR",
              variableCollectionId: "c1",
              valuesByMode: { L: { r: 0, g: 0, b: 0.5, a: 1 } },
            },
          } as any)[id] ?? null,
        getVariableCollectionByIdAsync: async () => null,
      },
    };
    const result = await exportToFlutter();

    // Both names camelCase to colorsBlue500; the second gets a numeric suffix
    // in the declarations AND in the const instance (no duplicate named arg).
    expect(result).toContain("final Color colorsBlue500;");
    expect(result).toContain("final Color colorsBlue5002;");
    expect(result).toContain("colorsBlue500: Color(0xFF0000FF),");
    expect(result).toContain("colorsBlue5002: Color(0xFF000080),");
    expect(result).toContain("colorsBlue5002: colorsBlue5002 ?? this.colorsBlue5002,");
  });

  it("suffixes colliding mode instance names (Dark Mode / Dark-Mode)", async () => {
    (globalThis as any).figma = {
      variables: {
        getLocalVariableCollectionsAsync: async () => [
          {
            id: "c1",
            name: "Primitives",
            modes: [
              { name: "Light", modeId: "L" },
              { name: "Dark Mode", modeId: "DM" },
              { name: "Dark-Mode", modeId: "DM2" },
            ],
            variableIds: ["blue"],
          },
        ],
        getVariableByIdAsync: async (id: string) =>
          id === "blue"
            ? {
                name: "Colors/Blue",
                resolvedType: "COLOR",
                variableCollectionId: "c1",
                valuesByMode: {
                  L: { r: 0, g: 0, b: 1, a: 1 },
                  DM: { r: 0, g: 0, b: 0.2, a: 1 },
                  DM2: { r: 0, g: 0, b: 0.1, a: 1 },
                },
              }
            : null,
        getVariableCollectionByIdAsync: async () => null,
      },
    };
    const result = await exportToFlutter();

    // Both mode names camelCase to darkMode; the second instance is suffixed
    // so every static const stays addressable.
    expect(result).toContain("static const Tokens darkMode = Tokens(");
    expect(result).toContain("static const Tokens darkMode2 = Tokens(");
    expect(result.match(/static const Tokens darkMode = Tokens\(/g)?.length).toBe(1);
  });

  it("lists the used modes in the header", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToFlutter();

    expect(result).toContain("// Modes: Primitives → Light");
  });
});
