import { rgbToHex8 } from "./color";
import { toCssVar } from "./stringTransformation";
import { collectThemedTokens, type FlatToken } from "./collectionToTailwindPreset";
import type { ExportSelection } from "../types.d";

/** Categories whose FLOAT values are lengths (emitted as "Npx"). */
const PX_CATEGORIES = new Set(["spacing", "borderRadius", "fontSize", "letterSpacing"]);

/**
 * Converts a camelCase category key (fontWeight, fontFamily, ...) to kebab-case
 * for use in the SCSS variable name.
 * @param category - The token category key
 * @returns The kebab-case category
 */
function kebabCategory(category: string): string {
    return category.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/**
 * Formats a concrete token value as an SCSS value: colors as hex, lengths as
 * "Npx", durations as "Nms", other floats as unitless numbers (rounded to 3
 * decimals), booleans as-is, strings quoted (an unquoted string containing
 * spaces becomes a list, `//` starts a comment that swallows the rest of the
 * line, and `#`/`"` break the syntax — matching the quoted strings of the
 * other CSS-target exporters).
 * @param token - The flat token to format
 * @returns The SCSS value string
 */
function scssValue(token: FlatToken): string {
    switch (token.resolvedType) {
        case "COLOR":
            return rgbToHex8(token.value as RGBA);
        case "FLOAT": {
            const num = typeof token.value === "number" ? token.value : parseFloat(token.value as string);
            if (PX_CATEGORIES.has(token.category)) return `${num}px`;
            if (token.category === "transitionDuration") return `${num}ms`;
            return String(Math.round(num * 1000) / 1000);
        }
        case "BOOLEAN":
            return Boolean(token.value) ? "true" : "false";
        default:
            return scssString(token.value);
    }
}

/**
 * Quotes a string token value as an SCSS double-quoted string, escaping
 * backslashes, double quotes and newlines.
 * @param value - The concrete string value
 * @returns The quoted SCSS string literal
 */
function scssString(value: VariableValue): string {
    const escaped = String(value)
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/\r?\n/g, "\\a ");
    return `"${escaped}"`;
}

/**
 * Exports all local variable collections as SCSS variables (Style Dictionary
 * `scss/variables` style), one `$category-path: value;` per token. The default
 * variables use the first selected mode of each collection; every other
 * selected mode name (e.g. "Dark") becomes an extra `$theme-<mode>` map with
 * a complete set of entries (collections lacking that mode contribute their
 * default values). Aliases are resolved to concrete values.
 * @param selection - Optional export selection (omit to export everything)
 * @param prefix - Optional prefix prepended to each token family segment
 * @returns SCSS source string with one variable per token plus theme maps
 */
export const exportToSCSS = async (
    selection?: ExportSelection,
    prefix: string = ""
): Promise<string> => {
    try {
        const { defaultTokens, usedModes, extraThemes } = await collectThemedTokens(selection, prefix);

        const header = [
            "// SCSS variables generated by Variform.",
            "// Static export: values come from the first selected mode of each collection",
            "// and aliases are resolved to concrete values.",
            ...(usedModes.length > 0 ? [`// Modes: ${usedModes.join("; ")}`] : []),
            ...(prefix ? [`// Prefix: "${toCssVar(prefix)}"`] : []),
            ...(extraThemes.length > 0 ? [
                `// Themes: ${extraThemes.map((theme) => toCssVar(theme.mode)).join(", ")}`,
                // Per https://sass-lang.com/documentation/values/maps/ a theme map is
                // consumed with map.get(); a static file cannot switch themes at runtime.
                `// Consume theme maps with map.get($theme-${toCssVar(extraThemes[0].mode)}, "<name>") after \`@use "sass:map";\`.`,
                "// Note: static export — theme switching (e.g. `@media (prefers-color-scheme: dark)`)",
                "// must be wired up by the consumer; the maps only hold the values.",
            ] : []),
        ].join("\n");

        const tokenName = (token: FlatToken) => `${kebabCategory(token.category)}-${token.path.join("-")}`;

        const variables = defaultTokens.map(
            (token) => `$${tokenName(token)}: ${scssValue(token)};`
        );

        const themeMaps = extraThemes.map((theme) => {
            const entries = theme.tokens
                .map((token) => `  "${tokenName(token)}": ${scssValue(token)},`)
                .join("\n");
            return `$theme-${toCssVar(theme.mode)}: (\n${entries}\n);`;
        });

        return [header, variables.join("\n"), ...themeMaps].filter(Boolean).join("\n\n") + "\n";
    } catch (err) {
        console.error(err);
        return `/* Something went wrong while converting to SCSS variables:
            ${err}*/`;
    }
};
