import { describe, it, expect, afterEach } from "vitest";
import { exportToAndroid, rgbaToArgbHex } from "./collectionToAndroid";

/* ----------------------------- pure functions ---------------------------- */

describe("rgbaToArgbHex", () => {
  it("emits uppercase ARGB with alpha first (FF when opaque)", () => {
    expect(rgbaToArgbHex({ r: 0, g: 0, b: 1, a: 1 })).toBe("#FF0000FF");
  });

  it("emits the alpha channel for translucent colors", () => {
    expect(rgbaToArgbHex({ r: 0, g: 0, b: 0, a: 0.5 })).toBe("#80000000");
  });
});

/* ------------------------- end-to-end with a mock ------------------------ */

function makeFigmaMock(extraMode?: { name: string; modeId: string }) {
  const collection = {
    id: "c1",
    name: "Primitives",
    modes: [
      { name: "Light", modeId: "L" },
      { name: "Dark", modeId: "D" },
      ...(extraMode ? [extraMode] : []),
    ],
    variableIds: ["blue500", "overlayDim", "spacing4", "fontSizeBody", "familySans", "bgPrimary", "welcome"],
  };

  const vars: Record<string, any> = {
    blue500: {
      name: "Colors/Blue/500",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { r: 0, g: 0, b: 1, a: 1 },
        D: { r: 0, g: 0, b: 0.2, a: 1 },
      },
    },
    overlayDim: {
      name: "Overlay/Dim",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { r: 0, g: 0, b: 0, a: 0.5 },
        D: { r: 0, g: 0, b: 0, a: 0.5 },
      },
    },
    spacing4: {
      name: "Spacing/4",
      resolvedType: "FLOAT",
      variableCollectionId: "c1",
      valuesByMode: { L: 16, D: 16 },
    },
    fontSizeBody: {
      name: "Font Size/Body",
      resolvedType: "FLOAT",
      variableCollectionId: "c1",
      valuesByMode: { L: 14, D: 14 },
    },
    familySans: {
      name: "Font Family/Sans",
      resolvedType: "STRING",
      variableCollectionId: "c1",
      valuesByMode: { L: "Inter", D: "Inter" },
    },
    bgPrimary: {
      name: "Background/Primary",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { type: "VARIABLE_ALIAS", id: "blue500" },
        D: { type: "VARIABLE_ALIAS", id: "blue500" },
      },
    },
    welcome: {
      name: "Copy/Welcome",
      resolvedType: "STRING",
      variableCollectionId: "c1",
      valuesByMode: {
        L: `We're "live" & up`,
        D: `We're "live" & up`,
      },
    },
  };

  if (extraMode) {
    for (const id of Object.keys(vars)) {
      vars[id].valuesByMode[extraMode.modeId] = vars[id].valuesByMode.D;
    }
  }

  return {
    variables: {
      getLocalVariableCollectionsAsync: async () => [collection],
      getVariableByIdAsync: async (id: string) => vars[id] ?? null,
      getVariableCollectionByIdAsync: async (id: string) => (id === "c1" ? collection : null),
    },
  };
}

describe("exportToAndroid", () => {
  afterEach(() => {
    delete (globalThis as any).figma;
  });

  it("wraps the tokens in a <resources> document with the Variform header", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    expect(result).toContain('<?xml version="1.0" encoding="utf-8"?>');
    expect(result).toContain("<!-- Android resources generated by Variform.");
    expect(result).toContain("<resources>");
    expect(result).toContain("</resources>");
    expect(result).toContain("    <color name=");  // 4-space indent
    expect(result).not.toContain("import(");
  });

  it("names resources as snake_case of category + path segments", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    expect(result).toContain('name="colors_blue_500"');
    expect(result).toContain('name="colors_overlay_dim"');
    expect(result).toContain('name="spacing_4"');
    expect(result).toContain('name="font_family_sans"');
    expect(result).toContain('name="colors_background_primary"');
  });

  it("emits colors as uppercase ARGB hex, alpha first", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    expect(result).toContain('<color name="colors_blue_500">#FF0000FF</color>');
    expect(result).toContain('<color name="colors_overlay_dim">#80000000</color>');
  });

  it("emits lengths as dp dimens", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    expect(result).toContain('<dimen name="spacing_4">16dp</dimen>');
    // "Font Size/Body" categorizes as spacing (the 'size' heuristic wins over
    // 'font'), so it lands in the spacing family with dp, not sp.
    expect(result).toContain('<dimen name="spacing_font_size_body">14dp</dimen>');
  });

  it("emits STRING values as escaped <string> resources", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    expect(result).toContain('<string name="font_family_sans">Inter</string>');
  });

  it("escapes quotes with aapt backslash escapes and & as an XML entity", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    // aapt rejects &apos;/&quot; in <string> resources ("Apostrophe not
    // preceded by \"), so quotes must be \' and \"; & stays an XML entity.
    expect(result).toContain(`<string name="other_copy_welcome">We\\'re \\"live\\" &amp; up</string>`);
    expect(result).not.toContain("&apos;");
    expect(result).not.toContain("&quot;");
  });

  it("resolves aliases to the terminal color value", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    expect(result).toContain('<color name="colors_background_primary">#FF0000FF</color>');
    expect(result).not.toContain("VARIABLE_ALIAS");
  });

  it("applies the prefix to the family segment", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid(undefined, "acme");

    expect(result).toContain('name="colors_acme_blue_500"');
    expect(result).not.toContain('name="colors_blue_500"');
  });

  it("appends a second <resources> block for the Dark mode with a values-night comment", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid();

    // Header documents the official dark-theme mechanism; default block comes first.
    expect(result).toContain("https://developer.android.com/develop/ui/views/theming/darktheme");
    expect(result).toContain("Theme.MaterialComponents.DayNight");
    expect(result.indexOf("<resources>")).toBeLessThan(
      result.indexOf("<!-- Move this block to res/values-night/<file>.xml (same file name as the default res/values/ file) -->")
    );
    expect(result.split("<resources>").length - 1).toBe(2);

    // Default block keeps the Light values.
    const [defaultBlock, darkBlock] = result.split(
      "<!-- Move this block to res/values-night/<file>.xml (same file name as the default res/values/ file) -->"
    );
    expect(defaultBlock).toContain('<color name="colors_blue_500">#FF0000FF</color>');

    // Dark block: dark color, and the alias resolved to the dark value.
    expect(darkBlock).toContain('<color name="colors_blue_500">#FF000033</color>');
    expect(darkBlock).toContain('<color name="colors_background_primary">#FF000033</color>');
    expect(darkBlock).not.toContain("#FF0000FF");
    expect(result).not.toContain("import(");
  });

  it("flags non-night modes as having no Android qualifier instead of inventing a directory", async () => {
    (globalThis as any).figma = makeFigmaMock({ name: "High Contrast", modeId: "HC" });
    const result = await exportToAndroid();

    expect(result.split("<resources>").length - 1).toBe(3);
    // The Dark mode still maps to the documented values-night qualifier.
    expect(result).toContain("res/values-night/<file>.xml");
    // "High Contrast" has no valid values-<qualifier> directory: the output must
    // say so instead of emitting an invalid qualifier like values-high-contrast.
    expect(result).toContain(
      '<!-- No Android resource qualifier exists for mode "High Contrast": map it manually'
    );
    expect(result).not.toContain("values-high-contrast");
    expect(result).not.toContain("import(");
  });

  it("emits a single <resources> document when a single mode is selected", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToAndroid({ c1: ["L"] });

    expect(result.split("<resources>").length - 1).toBe(1);
    expect(result).not.toContain("values-night");
    expect(result).not.toContain("Move this block");
  });
});
