import { describe, it, expect, afterEach } from "vitest";
import { exportToSwift } from "./collectionToSwift";

function makeFigmaMock() {
  const collection = {
    id: "c1",
    name: "Primitives",
    modes: [
      { name: "Light", modeId: "L" },
      { name: "Dark", modeId: "D" },
    ],
    variableIds: ["blue500", "overlayDim", "spacing4", "fontSizeBody", "familySans", "familyEscape", "spacingHuge", "bgPrimary"],
  };

  const vars: Record<string, any> = {
    blue500: {
      name: "Colors/Blue/500",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { r: 0, g: 0, b: 1, a: 1 },
        D: { r: 0, g: 0, b: 0.2, a: 1 },
      },
    },
    overlayDim: {
      name: "Overlay/Dim",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { r: 0, g: 0, b: 0, a: 0.5 },
        D: { r: 0, g: 0, b: 0, a: 0.5 },
      },
    },
    spacing4: {
      name: "Spacing/4",
      resolvedType: "FLOAT",
      variableCollectionId: "c1",
      valuesByMode: { L: 16, D: 16 },
    },
    fontSizeBody: {
      name: "Font Size/Body",
      resolvedType: "FLOAT",
      variableCollectionId: "c1",
      valuesByMode: { L: 14, D: 14 },
    },
    familySans: {
      name: "Font Family/Sans",
      resolvedType: "STRING",
      variableCollectionId: "c1",
      valuesByMode: { L: "Inter", D: "Inter" },
    },
    familyEscape: {
      name: "Font Family/Escape",
      resolvedType: "STRING",
      variableCollectionId: "c1",
      valuesByMode: {
        L: 'C:\\fonts\\Inter "Bold"\nFallback',
        D: 'C:\\fonts\\Inter "Bold"\nFallback',
      },
    },
    spacingHuge: {
      name: "Spacing/Huge",
      resolvedType: "FLOAT",
      variableCollectionId: "c1",
      valuesByMode: { L: 1e21, D: 1e21 },
    },
    bgPrimary: {
      name: "Background/Primary",
      resolvedType: "COLOR",
      variableCollectionId: "c1",
      valuesByMode: {
        L: { type: "VARIABLE_ALIAS", id: "blue500" },
        D: { type: "VARIABLE_ALIAS", id: "blue500" },
      },
    },
  };

  return {
    variables: {
      getLocalVariableCollectionsAsync: async () => [collection],
      getVariableByIdAsync: async (id: string) => vars[id] ?? null,
      getVariableCollectionByIdAsync: async (id: string) => (id === "c1" ? collection : null),
    },
  };
}

describe("exportToSwift", () => {
  afterEach(() => {
    delete (globalThis as any).figma;
  });

  it("wraps the tokens in a public enum with the Variform header", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    expect(result).toContain("// Swift tokens generated by Variform.");
    expect(result).toContain("import UIKit");
    expect(result).toContain("public enum Tokens {");
    expect(result).toContain("    public static let colorsBlue500");  // 4-space indent
    expect(result.trimEnd().endsWith("}")).toBe(true);
    expect(result).not.toContain("import(");
  });

  it("names constants as camelCase of category + path segments", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    expect(result).toContain("colorsBlue500");
    expect(result).toContain("colorsOverlayDim");
    expect(result).toContain("spacing4");
    expect(result).toContain("fontFamilySans");
    // "Background/Primary" categorizes as colors (the 'background' keyword),
    // so the constant carries the colors prefix like any other color token.
    expect(result).toContain("colorsBackgroundPrimary");
  });

  it("emits UIColor with 3-decimal 0-1 channels", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    expect(result).toContain(
      "colorsBlue500 = UIColor(red: 0.000, green: 0.000, blue: 1.000, alpha: 1.000)"
    );
  });

  it("keeps the alpha channel for translucent colors", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    expect(result).toContain(
      "colorsOverlayDim = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.500)"
    );
  });

  it("emits FLOAT values as CGFloat, always with a decimal", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    expect(result).toContain("spacing4: CGFloat = 16.0");
    // "Font Size/Body" categorizes as spacing (the 'size' heuristic wins over
    // 'font'), so the constant name reflects that category.
    expect(result).toContain("spacingFontSizeBody: CGFloat = 14.0");
  });

  it("emits STRING values quoted", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    expect(result).toContain('fontFamilySans = "Inter"');
  });

  it("escapes backslashes, quotes, and newlines in STRING values", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    // Raw value: C:\fonts\Inter "Bold"<newline>Fallback — a literal newline
    // or unescaped backslash inside a Swift string literal would not compile.
    expect(result).toContain(
      'fontFamilyEscape = "C:\\\\fonts\\\\Inter \\"Bold\\"\\nFallback"'
    );
    expect(result).not.toContain("\nFallback");
  });

  it("keeps exponential notation for very large FLOATs (no dangling .0)", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    // `${1e21}` is "1e+21"; appending ".0" would emit invalid Swift.
    expect(result).toContain("spacingHuge: CGFloat = 1e+21");
    expect(result).not.toContain("1e+21.0");
  });

  it("resolves aliases to the terminal color value", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    expect(result).toContain(
      "colorsBackgroundPrimary = UIColor(red: 0.000, green: 0.000, blue: 1.000, alpha: 1.000)"
    );
    expect(result).not.toContain("VARIABLE_ALIAS");
  });

  it("applies the prefix to the family segment", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift(undefined, "acme");

    expect(result).toContain("colorsAcmeBlue500");
    expect(result).not.toContain("colorsBlue500");
  });

  it("documents Apple's adaptive-color mechanism and the static-export gap in the header", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    // Per https://developer.apple.com/documentation/uikit/supporting-dark-mode-in-your-interface,
    // Dark Mode colors should adapt via UIColor(named:) asset variants or
    // UIColor(dynamicProvider:) — the header must point at both.
    expect(result).toContain("UIColor(dynamicProvider:)");
    expect(result).toContain("UIColor(named:)");
    expect(result).toContain(
      "// https://developer.apple.com/documentation/uikit/supporting-dark-mode-in-your-interface"
    );
    // The gap: fixed component values do not adapt; the header must say so.
    expect(result).toContain("will NOT adapt to the");
    // The documented light/dark idioms appear as comments, never as emitted
    // adaptive code — every color constant stays a fixed UIColor initializer.
    expect(result).not.toMatch(/^public.*UIColor\(/m);
    expect(result).not.toContain("import(");
  });

  it("emits a TokensDark enum after the default enum with the Dark values", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift();

    // Default enum keeps the Light values and comes first.
    expect(result.indexOf("public enum Tokens {")).toBeLessThan(
      result.indexOf("public enum TokensDark {")
    );
    expect(result).toContain(
      "colorsBlue500 = UIColor(red: 0.000, green: 0.000, blue: 1.000, alpha: 1.000)"
    );

    // Dark variant: dark color, and the alias resolved to the dark value.
    const darkEnum = result.slice(result.indexOf("public enum TokensDark {"));
    expect(darkEnum).toContain(
      "colorsBlue500 = UIColor(red: 0.000, green: 0.000, blue: 0.200, alpha: 1.000)"
    );
    expect(darkEnum).toContain(
      "colorsBackgroundPrimary = UIColor(red: 0.000, green: 0.000, blue: 0.200, alpha: 1.000)"
    );
    expect(darkEnum).not.toContain("blue: 1.000");
    expect(result).not.toContain("import(");
  });

  it("emits no theme variant when a single mode is selected", async () => {
    (globalThis as any).figma = makeFigmaMock();
    const result = await exportToSwift({ c1: ["L"] });

    expect(result).toContain("public enum Tokens {");
    expect(result).not.toContain("TokensDark");
  });
});
