import { rgbToHex8 } from "./color";
import { toCssVar, toCamelCase } from "./stringTransformation";
import { collectThemedTokens, setNestedPath } from "./collectionToTailwindPreset";
import type { FlatToken } from "./collectionToTailwindPreset";
import type { ExportSelection } from "../types.d";

type ThemeDictionary = Record<string, any>;

/**
 * Formats a concrete token value for React Native: colors as hex strings
 * (hex8 when translucent — React Native accepts #rrggbbaa), FLOATs as raw
 * numbers rounded to 3 decimals (never "16px" — React Native style values
 * are unitless), booleans and strings as-is.
 * @param resolvedType - Type of the (resolved) value
 * @param value - The concrete value (aliases already resolved)
 * @returns The value as it should appear in the theme object
 */
function tokenValue(resolvedType: string, value: VariableValue): string | number | boolean {
    if (resolvedType === "COLOR") return rgbToHex8(value as RGBA);
    if (resolvedType === "FLOAT") return Math.round(Number(value) * 1000) / 1000;
    if (resolvedType === "BOOLEAN") return Boolean(value);
    return String(value);
}

/**
 * Serializes the dictionary as a JS object literal, unquoting keys that are
 * valid identifiers (kebab-case and numeric keys stay quoted).
 */
function serializeDictionary(dictionary: ThemeDictionary): string {
    return JSON.stringify(dictionary, null, 2)
        .replace(/"([A-Za-z_$][A-Za-z0-9_$]*)":/g, "$1:");
}

/**
 * Builds the nested theme dictionary (category → path → value) from a flat
 * token list.
 * @param tokens - The flat tokens of one theme variant
 * @returns The nested theme dictionary
 */
function buildThemeDictionary(tokens: FlatToken[]): ThemeDictionary {
    const theme: ThemeDictionary = {};
    for (const token of tokens) {
        setNestedPath(theme, [token.category, ...token.path], tokenValue(token.resolvedType, token.value));
    }
    return theme;
}

/**
 * Quotes a key unless it is a valid JS identifier, for use in the `themes`
 * map's object literal.
 */
function objectKey(key: string): string {
    return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

/**
 * Exports all local variable collections as a React Native / Expo theme
 * object. A theme is static, so values come from the first selected mode of
 * each collection and aliases are resolved to concrete values. Every
 * additional selected mode is emitted as its own complete theme variant
 * (`darkTheme`, `contrastTheme`, ...) after the default `theme`, and all
 * variants are gathered in a `themes` map keyed by camelCased mode name
 * (`light`, `dark`, ...) so the app can select one with React Native's
 * useColorScheme hook, as documented by Expo and React Native.
 * @param selection - Optional export selection (omit to export everything)
 * @param prefix - Optional prefix prepended to each token family segment
 * @returns TypeScript module string exporting the theme objects
 */
export const exportToReactNative = async (
    selection?: ExportSelection,
    prefix: string = ""
): Promise<string> => {
    try {
        const { defaultTokens, usedModes, extraThemes } = await collectThemedTokens(selection, prefix);

        // usedModes entries are "Collection → Mode"; the first collection's
        // default mode names the default theme's key in the `themes` map.
        const defaultKey = toCamelCase(usedModes[0]?.split("→").pop()?.trim() ?? "default");

        const header = [
            "/**",
            " * React Native / Expo theme generated by Variform.",
            " * Static theme: values come from the first selected mode of each",
            " * collection and aliases are resolved to concrete values.",
            ...(usedModes.length > 0 ? [` * Modes: ${usedModes.join("; ")}`] : []),
            ...(prefix ? [` * Prefix: "${toCssVar(prefix)}"`] : []),
            ...(extraThemes.length > 0
                ? [
                    ` * Themes: ${extraThemes.map((theme) => toCamelCase(theme.mode)).join(", ")}`,
                    " *",
                    " * Light/dark selection follows the Expo / React Native convention",
                    " * (https://docs.expo.dev/develop/user-interface/color-themes/): pick",
                    " * the active theme at runtime with the useColorScheme hook —",
                    " *   const colorScheme = useColorScheme();",
                    ` *   const activeTheme = themes[colorScheme ?? "${defaultKey}"];`,
                    ' * Set "userInterfaceStyle": "automatic" in app.json so useColorScheme',
                    " * follows the system appearance. The generated file stays static on",
                    " * purpose: the runtime switch lives in app code, per the docs.",
                ]
                : []),
            " */",
        ].join("\n");

        const modules = [
            `export const theme = ${serializeDictionary(buildThemeDictionary(defaultTokens))} as const;`,
            ...extraThemes.map(
                ({ mode, tokens }) =>
                    `export const ${toCamelCase(mode)}Theme = ${serializeDictionary(buildThemeDictionary(tokens))} as const;`
            ),
            ...(extraThemes.length > 0
                ? [
                    `export const themes = {\n${[
                        `  ${objectKey(defaultKey)}: theme`,
                        ...extraThemes
                            .filter(({ mode }) => toCamelCase(mode) !== defaultKey)
                            .map(({ mode }) => `  ${objectKey(toCamelCase(mode))}: ${toCamelCase(mode)}Theme`),
                    ].join(",\n")}\n} as const;`,
                ]
                : []),
        ];

        return `${header}\n${modules.join("\n\n")}\n`;
    } catch (err) {
        console.error(err);
        return `/* Something went wrong while converting to a React Native theme:
            ${err}*/`;
    }
};
